version: '3.5'
services:
  youtube-api:
    hostname: youtube-api
    image: youtube-api
    container_name: youtube-api
    build:
      context: ../ctr/google_api
      dockerfile: google_api_python.Dockerfile
    env_file:
      - ../ctr/google_api/resource/container/.env
    volumes:
      - ../src/google_api:/home
    user: root
    working_dir: /home
    networks:
      - default

  google-persistent-db:
    hostname: google-persistent-db
    image: google-persistent-db
    container_name: google-persistent-db
    build:
      context: ../ctr/persistent_db
      dockerfile: db_mysql.Dockerfile
    env_file:
      - ../ctr/persistent_db/resource/google_api/container/.env
    environment: 
      - TZ=Asia/Tokyo
    volumes:
      - ../ctr/persistent_db/resource/google_api/container/initdb.d:/docker-entrypoint-initdb.d
      - ../ctr/persistent_db/resource/google_api/container/data:/var/lib/mysql
    ports:
      - "31111:3306"
    user: root
    tty: True
    restart: unless-stopped
    networks:
      - default
      - lake
networks:
  lake:
    external: True
  default:
    name: youtube