version: '3.5'
services:
  youtube-api:
    hostname: youtube-api
    image: youtube-api
    container_name: youtube-api
    build:
      context: ../ctr/youtubeapi
      dockerfile: youtubeapi.Dockerfile
    env_file:
      - ../ctr/youtubeapi/resource/container/.env
    volumes:
      - ../src/youtubeapi:/home
    user: root
    tty: True
    working_dir: /home
    networks:
      - default

  youtube-persistent-db:
    hostname: youtube-persistent-db
    image: youtube-persistent-db
    container_name: youtube-persistent-db
    build:
      context: ../ctr/persistent_db
      dockerfile: db_mysql.Dockerfile
    env_file:
      - ../ctr/persistent_db/resource/container/.env
    environment: 
      - TZ=Asia/Tokyo
    volumes:
      - ../ctr/persistent_db/resource/container/initdb.d:/docker-entrypoint-initdb.d
      - ../ctr/persistent_db/resource/container/data:/var/lib/mysql
    ports:
      - "31111:3306"
    user: root
    tty: True
    restart: unless-stopped
    networks:
      - default
      - lake
networks:
  lake:
    external: True
  default:
    name: youtube